# Generated by Django 6.1.1 on 2026-09-20 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('day_of_week', models.IntegerField()),
                ('slot_code', models.CharField(max_length=16)),
                ('starts_at_local', models.TimeField()),
                ('ends_at_local', models.TimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'timetable_period_template',
            },
        ),
        migrations.CreateModel(
            name='CalendarException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('holiday', 'holiday'), ('exam', 'exam'), ('event', 'event')], max_length=16)),
                ('reason_key', models.CharField(blank=True, max_length=64, null=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'timetable_calendar_exception',
                'indexes': [models.Index(fields=['school_id', 'date', 'withdrawn'], name='timetable_c_school__e8f840_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'date', 'kind'), name='timetable_exception_unique_per_date_kind')],
            },
        ),
        migrations.CreateModel(
            name='TeacherUnavailable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('staff_id', models.UUIDField(db_index=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason_key', models.CharField(blank=True, max_length=64, null=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'timetable_teacher_unavailable',
                'indexes': [models.Index(fields=['school_id', 'staff_id', 'starts_at'], name='timetable_t_school__2a2d0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('year_id', models.UUIDField(db_index=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('superseded', 'superseded')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'timetable_version',
                'indexes': [models.Index(fields=['school_id', 'state', 'effective_from'], name='timetable_v_school__13f8c1_idx'), models.Index(fields=['school_id', 'year_id'], name='timetable_v_school__6e96bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('section_id', models.UUIDField(db_index=True)),
                ('subject_id', models.UUIDField()),
                ('teacher_id', models.UUIDField(db_index=True)),
                ('room_code', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.periodtemplate')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.timetableversion')),
            ],
            options={
                'db_table': 'timetable_slot',
            },
        ),
        migrations.AddField(
            model_name='periodtemplate',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='timetable.timetableversion'),
        ),
        migrations.CreateModel(
            name='SessionCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('timetable_session_id', models.UUIDField(db_index=True)),
                ('section_id', models.UUIDField(db_index=True)),
                ('cancelled', models.BooleanField(default=True)),
                ('reason_key', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='timetable.slot')),
            ],
            options={
                'db_table': 'timetable_session_cancellation',
                'indexes': [models.Index(fields=['school_id', 'date'], name='timetable_s_school__19376f_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'timetable_session_id'), name='timetable_cancellation_unique_per_session')],
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('timetable_session_id', models.UUIDField(db_index=True)),
                ('section_id', models.UUIDField(db_index=True)),
                ('subject_id', models.UUIDField()),
                ('original_teacher_id', models.UUIDField()),
                ('substitute_teacher_id', models.UUIDField(db_index=True)),
                ('reason', models.CharField(max_length=200)),
                ('valid_until', models.DateTimeField()),
                ('withdrawn', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions', to='timetable.slot')),
            ],
            options={
                'db_table': 'timetable_substitution',
                'indexes': [models.Index(fields=['school_id', 'date', 'withdrawn'], name='timetable_s_school__7e2cf2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('withdrawn', False)), fields=('school_id', 'date', 'slot'), name='timetable_substitution_unique_live_per_period')],
            },
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['timetable', 'section_id'], name='timetable_s_timetab_49aa13_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['timetable', 'teacher_id'], name='timetable_s_timetab_98cae2_idx'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('timetable', 'section_id', 'period'), name='timetable_slot_unique_section_period'),
        ),
        migrations.AddIndex(
            model_name='periodtemplate',
            index=models.Index(fields=['timetable', 'day_of_week'], name='timetable_p_timetab_77f3e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodtemplate',
            constraint=models.UniqueConstraint(fields=('timetable', 'day_of_week', 'slot_code'), name='timetable_period_unique_per_day'),
        ),
    ]
