# Generated by Django 6.1.1 on 2026-09-21 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('notice_id', models.UUIDField(db_index=True)),
                ('recipient_ids', models.JSONField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'communications_audience_snapshot',
            },
        ),
        migrations.CreateModel(
            name='CommunicationsPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(unique=True)),
                ('sms_configure_requires_2fa', models.BooleanField(default=False)),
                ('live_provider', models.CharField(default='fake', max_length=32)),
                ('channels_enabled', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'communications_policy',
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(unique=True)),
                ('secret_ref', models.CharField(max_length=200)),
                ('sender_id', models.CharField(max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'communications_provider_config',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('delivery_id', models.UUIDField(db_index=True)),
                ('attempted_at', models.DateTimeField()),
                ('outcome', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'communications_attempt',
                'indexes': [models.Index(fields=['delivery_id', 'attempted_at'], name='communicati_deliver_eaa7d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CallbackNonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('provider', models.CharField(max_length=32)),
                ('nonce', models.CharField(max_length=200)),
                ('consumed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'communications_callback_nonce',
                'constraints': [models.UniqueConstraint(fields=('school_id', 'provider', 'nonce'), name='communications_callback_nonce_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('recipient_ref', models.UUIDField()),
                ('channel', models.CharField(choices=[('in_app', 'in_app'), ('sms', 'sms')], max_length=16)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('payload_hash', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('queued', 'queued'), ('sending', 'sending'), ('accepted', 'accepted'), ('delivered', 'delivered'), ('failed', 'failed'), ('unknown', 'unknown')], default='queued', max_length=16)),
                ('provider_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('template_key', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=8)),
                ('variables', models.JSONField(default=dict)),
                ('rendered_body', models.TextField(default='')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'communications_delivery',
                'indexes': [models.Index(fields=['school_id', 'state'], name='communicati_school__9cc733_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'dedupe_key'), name='communications_delivery_school_dedupe_uniq')],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('key', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=8)),
                ('version', models.IntegerField(default=1)),
                ('body', models.TextField()),
                ('provider_template_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'communications_message_template',
                'constraints': [models.UniqueConstraint(fields=('school_id', 'key', 'locale', 'version'), name='communications_template_school_key_locale_ver_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('locale', models.CharField(max_length=8)),
                ('audience', models.JSONField()),
                ('state', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('audience_snapshot_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'communications_notice',
                'indexes': [models.Index(fields=['school_id', 'state'], name='communicati_school__16bc52_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerifiedContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('recipient_ref', models.UUIDField(db_index=True)),
                ('person_id', models.UUIDField()),
                ('channel', models.CharField(choices=[('in_app', 'in_app'), ('sms', 'sms')], max_length=16)),
                ('verified', models.BooleanField(default=True)),
                ('revoked', models.BooleanField(default=False)),
                ('purpose_allowed', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'communications_verified_contact',
                'constraints': [models.UniqueConstraint(fields=('school_id', 'recipient_ref'), name='communications_verified_contact_school_ref_uniq')],
            },
        ),
    ]
