# Generated by Django 6.1.1 on 2026-09-20 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('source_key', models.CharField(max_length=256)),
                ('charge_id', models.UUIDField()),
                ('amount_paise', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'pending'), ('requested', 'requested'), ('posted', 'posted'), ('failed', 'failed')], default='pending', max_length=16)),
                ('credit_id', models.UUIDField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=128, null=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'transport_adjustment_request',
                'indexes': [models.Index(fields=['school_id', 'charge_id'], name='transport_a_school__03401e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('participation_id', models.UUIDField(db_index=True)),
                ('period', models.CharField(max_length=7)),
                ('charge_kind', models.CharField(choices=[('period', 'period'), ('adjustment', 'adjustment')], default='period', max_length=16)),
                ('source_key', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('requested', 'requested'), ('posted', 'posted'), ('blocked', 'blocked'), ('failed', 'failed')], default='pending', max_length=16)),
                ('charge_id', models.UUIDField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=128, null=True)),
                ('amount_paise', models.BigIntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'transport_billing_request',
                'indexes': [models.Index(fields=['school_id', 'period', 'state'], name='transport_b_school__217447_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'participation_id', 'period', 'charge_kind'), name='transport_billing_school_part_period_kind_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('label', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'transport_bus',
                'indexes': [models.Index(fields=['school_id', 'label'], name='transport_b_school__c0683c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('bus_id', models.UUIDField(blank=True, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('fee_plan_id', models.UUIDField()),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'transport_participation',
                'indexes': [models.Index(fields=['school_id', 'student_id'], name='transport_p_school__ce22c8_idx'), models.Index(fields=['school_id', 'from_date', 'to_date'], name='transport_p_school__0626b0_idx')],
            },
        ),
    ]
