# Generated by Django 6.1.1 on 2026-09-20 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('source_key', models.CharField(max_length=256)),
                ('amount_paise', models.BigIntegerField()),
                ('balance_paise', models.BigIntegerField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'open'), ('partial', 'partial'), ('paid', 'paid'), ('credited', 'credited'), ('reversed', 'reversed')], default='open', max_length=16)),
                ('description_key', models.CharField(blank=True, max_length=128, null=True)),
                ('version', models.IntegerField(default=1)),
                ('posted_at', models.DateTimeField()),
                ('payload_fingerprint', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'fees_charge',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('amount_paise', models.BigIntegerField()),
                ('remaining_paise', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('source_key', models.CharField(max_length=256)),
                ('kind', models.CharField(choices=[('concession', 'concession'), ('overpayment', 'overpayment'), ('adjustment', 'adjustment')], max_length=16)),
                ('posted_at', models.DateTimeField()),
                ('payload_fingerprint', models.CharField(default='', max_length=64)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='fees.charge')),
            ],
            options={
                'db_table': 'fees_credit',
                'unique_together': {('school_id', 'source_key')},
            },
        ),
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('label_key', models.CharField(max_length=128)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'fees_feehead',
                'unique_together': {('school_id', 'code')},
            },
        ),
        migrations.AddField(
            model_name='charge',
            name='fee_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='fees.feehead'),
        ),
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('version', models.IntegerField()),
                ('applicability', models.JSONField(default=dict)),
                ('schedule', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'fees_feeplan',
                'unique_together': {('school_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('number', models.CharField(max_length=32)),
                ('amount_paise', models.BigIntegerField()),
                ('method', models.CharField(choices=[('cash', 'cash'), ('bank', 'bank'), ('upi', 'upi')], max_length=8)),
                ('reference', models.CharField(blank=True, max_length=128, null=True)),
                ('posted_at', models.DateTimeField()),
                ('reversed', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('remaining_paise', models.BigIntegerField()),
            ],
            options={
                'db_table': 'fees_payment',
                'indexes': [models.Index(fields=['school_id', 'student_id', 'posted_at'], name='fees_paymen_school__6374d8_idx')],
                'unique_together': {('school_id', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('amount_paise', models.BigIntegerField()),
                ('reversed', models.BooleanField(default=False)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fees.charge')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fees.payment')),
            ],
            options={
                'db_table': 'fees_allocation',
            },
        ),
        migrations.CreateModel(
            name='PaymentIdempotency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_rows', to='fees.payment')),
            ],
            options={
                'db_table': 'fees_paymentidempotency',
            },
        ),
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('civil_date', models.DateField()),
                ('next_value', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'fees_receiptsequence',
                'unique_together': {('school_id', 'civil_date')},
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('amount_paise', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='fees.credit')),
            ],
            options={
                'db_table': 'fees_refundrecord',
            },
        ),
        migrations.CreateModel(
            name='Reversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('reason', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='fees.payment')),
            ],
            options={
                'db_table': 'fees_reversal',
            },
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['school_id', 'student_id'], name='fees_charge_school__ba80a3_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['school_id', 'due_date'], name='fees_charge_school__f92365_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='charge',
            unique_together={('school_id', 'source_key')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentidempotency',
            unique_together={('school_id', 'idempotency_key')},
        ),
    ]
