# Generated by Django 6.1.1 on 2026-09-19 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('code', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('requires_recent_two_factor', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'access_permission',
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('school_id', models.UUIDField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'access_policy_version',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('is_owner_role', models.BooleanField(default=False)),
                ('requires_two_factor', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'access_role',
                'constraints': [models.UniqueConstraint(fields=('school_id', 'name'), name='access_role_unique_name_per_school')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('login_name', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=256)),
                ('display_name', models.CharField(max_length=200)),
                ('person_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('password_confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'access_user',
                'indexes': [models.Index(fields=['school_id', 'active'], name='access_user_school__ec65dd_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'login_name'), name='access_user_unique_login_per_school')],
            },
        ),
        migrations.CreateModel(
            name='TotpFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('encrypted_secret', models.BinaryField()),
                ('state', models.CharField(db_index=True, max_length=16)),
                ('last_accepted_step', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='access.user')),
            ],
            options={
                'db_table': 'access_totp_factor',
                'indexes': [models.Index(fields=['user', 'state'], name='access_totp_user_id_7c3e41_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('user',), name='access_one_active_factor_per_user')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('auth_level', models.CharField(choices=[('password', 'Password only'), ('password_totp', 'Password and TOTP'), ('recovery', 'Recovery code')], max_length=20)),
                ('auth_time', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent_family', models.CharField(blank=True, default='unknown', max_length=40)),
                ('created_by_challenge_id', models.UUIDField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='access.user')),
            ],
            options={
                'db_table': 'access_session',
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='access_sess_user_id_80de21_idx'), models.Index(fields=['school_id', 'revoked_at'], name='access_sess_school__69d8d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('code_hash', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by_session_id', models.UUIDField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='access.user')),
            ],
            options={
                'db_table': 'access_recovery_code',
                'indexes': [models.Index(fields=['user', 'used_at'], name='access_reco_user_id_68d814_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'code_hash'), name='access_recovery_code_unique_per_user')],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('reason', models.CharField(max_length=1000)),
                ('state', models.CharField(db_index=True, max_length=16)),
                ('created_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cases', to='access.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_cases', to='access.user')),
            ],
            options={
                'db_table': 'access_recovery_case',
                'indexes': [models.Index(fields=['user', 'state'], name='access_reco_user_id_da2ff7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('user',), name='access_one_pending_case_per_user')],
            },
        ),
        migrations.CreateModel(
            name='LoginChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.IntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_reason', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='access.user')),
            ],
            options={
                'db_table': 'access_login_challenge',
                'indexes': [models.Index(fields=['user', 'consumed_at'], name='access_logi_user_id_ff791f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('scope_type', models.CharField(choices=[('school', 'School'), ('section', 'Section'), ('subject', 'Subject'), ('self', 'Self')], max_length=16)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='access.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_grants', to='access.user')),
            ],
            options={
                'db_table': 'access_grant',
                'indexes': [models.Index(fields=['school_id', 'action'], name='access_gran_school__66b0bf_idx'), models.Index(fields=['role', 'action'], name='access_gran_role_id_99595b_idx'), models.Index(fields=['user', 'action'], name='access_gran_user_id_d41da8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('role__isnull', False), ('user__isnull', True)), models.Q(('role__isnull', True), ('user__isnull', False)), _connector='OR'), name='access_grant_exactly_one_holder'), models.CheckConstraint(condition=models.Q(models.Q(('scope_id__isnull', True), ('scope_type__in', ['school', 'self'])), models.Q(('scope_id__isnull', False), ('scope_type__in', ['section', 'subject'])), _connector='OR'), name='access_grant_scope_id_matches_type')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('granted_at', models.DateTimeField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='access.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='access.user')),
            ],
            options={
                'db_table': 'access_user_role',
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='access_user_role_unique')],
            },
        ),
    ]
