# Generated by Django 6.1.1 on 2026-09-21 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(unique=True)),
                ('retention_mode', models.CharField(default='economical', max_length=32)),
                ('grace_days', models.IntegerField(default=7)),
                ('max_bytes_per_page', models.IntegerField(default=12582912)),
                ('max_megapixels', models.IntegerField(default=40)),
                ('max_batch_pages', models.IntegerField(default=40)),
                ('long_edge_px', models.IntegerField(default=2400)),
                ('webp_quality', models.IntegerField(default=85)),
                ('signed_read_seconds', models.IntegerField(default=60)),
                ('retention_requires_2fa', models.BooleanField(default=True)),
                ('policy_version', models.CharField(default='economical_v1', max_length=64)),
            ],
            options={
                'db_table': 'files_policy',
            },
        ),
        migrations.CreateModel(
            name='PurgeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('source_id', models.UUIDField(db_index=True)),
                ('file_id', models.UUIDField(db_index=True)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('blocked', 'blocked'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=16)),
                ('block_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files_purge_job',
            },
        ),
        migrations.CreateModel(
            name='QualityReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('file_id', models.UUIDField(db_index=True)),
                ('candidate_version', models.IntegerField()),
                ('actor_id', models.UUIDField()),
                ('readability_confirmed', models.BooleanField(default=True)),
                ('confirmed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'files_quality_review',
            },
        ),
        migrations.CreateModel(
            name='SourceObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('upload_session_id', models.UUIDField(blank=True, null=True)),
                ('storage_key', models.CharField(max_length=512)),
                ('sha256', models.CharField(max_length=64)),
                ('byte_size', models.IntegerField()),
                ('mime', models.CharField(max_length=128)),
                ('backup_verified', models.BooleanField(default=False)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'files_source_object',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('file_id', models.UUIDField(db_index=True)),
                ('version', models.IntegerField()),
                ('storage_key', models.CharField(max_length=512)),
                ('sha256', models.CharField(max_length=64)),
                ('byte_size', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('profile_version', models.CharField(max_length=64)),
                ('mime', models.CharField(default='image/webp', max_length=128)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'files_candidate',
                'constraints': [models.UniqueConstraint(fields=('file_id', 'version'), name='files_candidate_file_version_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Derivative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('file_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(max_length=32)),
                ('version', models.IntegerField()),
                ('storage_key', models.CharField(max_length=512)),
                ('sha256', models.CharField(max_length=64)),
                ('mime', models.CharField(max_length=128)),
                ('byte_size', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'files_derivative',
                'indexes': [models.Index(fields=['file_id', 'kind', 'version'], name='files_deriv_file_id_4fbbb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidencePin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('file_id', models.UUIDField(db_index=True)),
                ('version', models.IntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('binding_id', models.UUIDField(unique=True)),
                ('pinned_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'files_evidence_pin',
                'indexes': [models.Index(fields=['file_id', 'version'], name='files_evide_file_id_7339a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('purpose', models.CharField(choices=[('answer_sheet', 'answer_sheet'), ('import_csv', 'import_csv'), ('import_xlsx', 'import_xlsx'), ('report_pdf', 'report_pdf'), ('report_csv', 'report_csv'), ('report_xlsx', 'report_xlsx')], max_length=32)),
                ('state', models.CharField(choices=[('processing', 'processing'), ('candidate_ready', 'candidate_ready'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('purging', 'purging')], default='processing', max_length=32)),
                ('source_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('subject_person_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('canonical_version', models.IntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('byte_size', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('profile_version', models.CharField(blank=True, max_length=64, null=True)),
                ('review_confirmed', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('legal_hold', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'files_file',
                'indexes': [models.Index(fields=['school_id', 'state'], name='files_file_school__3804e9_idx'), models.Index(fields=['school_id', 'sha256'], name='files_file_school__d85b14_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField()),
                ('purpose', models.CharField(choices=[('answer_sheet', 'answer_sheet'), ('import_csv', 'import_csv'), ('import_xlsx', 'import_xlsx'), ('report_pdf', 'report_pdf'), ('report_csv', 'report_csv'), ('report_xlsx', 'report_xlsx')], max_length=32)),
                ('client_name', models.CharField(max_length=255)),
                ('declared_bytes', models.IntegerField()),
                ('mime', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('open', 'open'), ('completed', 'completed'), ('expired', 'expired'), ('abandoned', 'abandoned')], default='open', max_length=16)),
                ('quarantine_key', models.CharField(max_length=512)),
                ('put_token', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('max_bytes', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'files_upload_session',
                'indexes': [models.Index(fields=['school_id', 'state', 'expires_at'], name='files_uploa_school__9fb102_idx')],
            },
        ),
    ]
