# Generated by Django 6.1.1 on 2026-09-21 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('job_id', models.UUIDField(db_index=True)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('result', models.JSONField(default=dict)),
                ('applied_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'exchange_commit_batch',
            },
        ),
        migrations.CreateModel(
            name='ExchangePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(unique=True)),
                ('formula_neutralization_prefix', models.CharField(default='\t', max_length=2)),
                ('malayalam_pdf_font_bundle', models.CharField(default='', max_length=100)),
                ('signed_read_seconds', models.IntegerField(default=120)),
                ('commit_requires_2fa', models.BooleanField(default=False)),
                ('commit_chunk_rows', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'exchange_policy',
            },
        ),
        migrations.CreateModel(
            name='Supersession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('old_report_id', models.UUIDField(db_index=True)),
                ('new_report_id', models.UUIDField()),
                ('reason', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'exchange_supersession',
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField()),
                ('dataset', models.CharField(choices=[('attendance_summary', 'attendance_summary'), ('progress', 'progress'), ('at_risk', 'at_risk'), ('ptm_summary', 'ptm_summary'), ('class_roster', 'class_roster'), ('subject_summary', 'subject_summary')], max_length=32)),
                ('filters', models.JSONField(default=dict)),
                ('requested_fields', models.JSONField(default=list)),
                ('field_grants', models.JSONField(default=list)),
                ('format', models.CharField(max_length=8)),
                ('locale', models.CharField(max_length=8)),
                ('state', models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='queued', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('artifact_file_id', models.UUIDField(blank=True, null=True)),
                ('artifact_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('failure_message_key', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'exchange_export_job',
                'indexes': [models.Index(fields=['school_id', 'state'], name='exchange_ex_school__d5b9b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField()),
                ('dataset', models.CharField(choices=[('enrolments', 'enrolments'), ('opening_balances', 'opening_balances'), ('results', 'results'), ('library_loans', 'library_loans')], max_length=32)),
                ('file_ref', models.UUIDField()),
                ('state', models.CharField(choices=[('validating', 'validating'), ('validated', 'validated'), ('validation_failed', 'validation_failed'), ('committing', 'committing'), ('applied', 'applied'), ('commit_failed', 'commit_failed')], default='validating', max_length=24)),
                ('source_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('validation_version', models.IntegerField(default=0)),
                ('template_version', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=64)),
                ('mode', models.CharField(default='validate', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('accepted_count', models.IntegerField(default=0)),
                ('applied_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('commit_key', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'exchange_import_job',
                'indexes': [models.Index(fields=['school_id', 'state'], name='exchange_im_school__2bdd82_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('job_id', models.UUIDField(db_index=True)),
                ('number', models.IntegerField()),
                ('external_key', models.CharField(default='', max_length=300)),
                ('validation_errors', models.JSONField(default=list)),
                ('state', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('applied', 'applied')], default='accepted', max_length=16)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'exchange_import_row',
                'indexes': [models.Index(fields=['job_id', 'state'], name='exchange_im_job_id_b03b23_idx')],
                'constraints': [models.UniqueConstraint(fields=('job_id', 'number'), name='exchange_import_row_job_number_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ReportCardJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField()),
                ('publication_id', models.UUIDField()),
                ('student_id', models.UUIDField()),
                ('locale', models.CharField(max_length=8)),
                ('template_version', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='queued', max_length=16)),
                ('report_id', models.UUIDField(blank=True, null=True)),
                ('failure_message_key', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'exchange_report_card_job',
                'indexes': [models.Index(fields=['school_id', 'state'], name='exchange_re_school__9c184e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('type', models.CharField(max_length=32)),
                ('source_revision_ids', models.JSONField(default=list)),
                ('policy_versions', models.JSONField(default=list)),
                ('locale', models.CharField(max_length=8)),
                ('artifact_ref', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('ready', 'ready'), ('superseded', 'superseded'), ('revoked', 'revoked')], default='pending', max_length=16)),
                ('superseded_by', models.UUIDField(blank=True, null=True)),
                ('publication_id', models.UUIDField(blank=True, null=True)),
                ('student_id', models.UUIDField(blank=True, null=True)),
                ('template_version', models.CharField(default='', max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'exchange_report_snapshot',
                'indexes': [models.Index(fields=['school_id', 'state'], name='exchange_re_school__8ca7e6_idx')],
            },
        ),
    ]
