# Generated by Django 6.1.1 on 2026-09-20 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('participants', models.JSONField(default=list)),
                ('notes', models.TextField()),
                ('actions', models.JSONField(default=list)),
                ('visibility', models.CharField(choices=[('staff', 'staff'), ('guardian_visible', 'guardian_visible'), ('restricted', 'restricted')], max_length=32)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'performance_meeting',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('staff', 'staff'), ('guardian_visible', 'guardian_visible'), ('restricted', 'restricted')], max_length=32)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'performance_observation',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('topic', models.CharField(max_length=128)),
                ('level', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'performance_resource',
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('rule_version', models.IntegerField()),
                ('state', models.CharField(choices=[('open', 'open'), ('acknowledged', 'acknowledged'), ('dismissed', 'dismissed'), ('closed', 'closed')], default='open', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('source_refs', models.JSONField(default=list)),
                ('explanation_key', models.CharField(max_length=128)),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('reason', models.TextField(blank=True, null=True)),
                ('opened_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'performance_warning',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('goal', models.TextField()),
                ('owner_id', models.UUIDField()),
                ('review_date', models.DateField()),
                ('state', models.CharField(choices=[('active', 'active'), ('reviewed', 'reviewed'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='active', max_length=16)),
                ('visibility', models.CharField(choices=[('staff', 'staff'), ('guardian_visible', 'guardian_visible'), ('restricted', 'restricted')], max_length=32)),
                ('version', models.IntegerField(default=1)),
                ('resource_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'performance_intervention',
                'indexes': [models.Index(fields=['school_id', 'student_id'], name='performance_school__9f2d01_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('formula', models.CharField(max_length=64)),
                ('denominator', models.CharField(default='100', max_length=32)),
            ],
            options={
                'db_table': 'performance_metricdefinition',
                'unique_together': {('school_id', 'code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('window', models.CharField(max_length=32)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('metrics_json', models.JSONField(default=dict)),
                ('source_versions', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'performance_projection',
                'indexes': [models.Index(fields=['school_id', 'student_id', 'window'], name='performance_school__c5f3c4_idx')],
                'unique_together': {('school_id', 'student_id', 'window', 'subject_id')},
            },
        ),
        migrations.CreateModel(
            name='WarningHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(max_length=16)),
                ('to_state', models.CharField(max_length=16)),
                ('reason', models.TextField()),
                ('actor_id', models.UUIDField()),
                ('at', models.DateTimeField()),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='performance.warning')),
            ],
            options={
                'db_table': 'performance_warninghistory',
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WarningRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('threshold', models.CharField(max_length=32)),
                ('window', models.CharField(max_length=32)),
                ('minimum_samples', models.IntegerField(default=1)),
                ('exclusions', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'performance_warningrule',
                'unique_together': {('school_id', 'code', 'version')},
            },
        ),
        migrations.AddField(
            model_name='warning',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warnings', to='performance.warningrule'),
        ),
        migrations.AddIndex(
            model_name='warning',
            index=models.Index(fields=['school_id', 'student_id', 'state'], name='performance_school__19a5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='warning',
            index=models.Index(fields=['school_id', 'fingerprint', 'state'], name='performance_school__f797a1_idx'),
        ),
    ]
