"""Renders a per-module Docker Compose file.

Only the services the module declared are emitted, so a module with no
asynchronous work produces a stack with no broker and no worker. The project
name, database, volumes, queue and bucket are all namespaced, which is what lets
two developers -- or one developer running two modules -- work simultaneously.

Images are pinned BY DIGEST from ``infra/images.json``, so a retagged upstream
image cannot change a stack underneath someone.

Emits YAML as text with no third-party dependency, because ``dev.py`` must run on
a fresh checkout before anything is installed. The emitter handles only the small
subset of YAML used here; it is not a general serialiser.
"""

from __future__ import annotations

import json
import pathlib

from .modules import ModuleDeclaration
from .naming import ResourceNames

#: Container-internal ports. Host ports are allocated dynamically.
POSTGRES_PORT = 5432
REDIS_PORT = 6379
MINIO_API_PORT = 9000
MINIO_CONSOLE_PORT = 9001
API_PORT = 8000
FRONTEND_PORT = 5173

#: Local development credentials for containers only. These are NOT secrets:
#: the services bind to loopback on a dynamically allocated port and hold only
#: synthetic fixture data. Real secrets live in dev/secrets/, outside Git.
LOCAL_DB_USER = "school_dev"
LOCAL_DB_PASSWORD = "school_dev_local_only"
LOCAL_MINIO_USER = "school_dev"
LOCAL_MINIO_PASSWORD = "school_dev_local_only"


def load_images(repo_root: pathlib.Path) -> dict[str, str]:
    """Return image name -> fully pinned digest reference.

    Raises FileNotFoundError with a pointer to the file when the pin record is
    missing, rather than falling back to a floating tag.
    """
    path = repo_root / "infra" / "images.json"
    if not path.exists():
        raise FileNotFoundError(
            f"{path} is missing; images must be pinned by digest, never floated."
        )
    record = json.loads(path.read_text())
    return {
        name: f"{image['registry']}/{image['repository']}@{image['digest']}"
        for name, image in record["images"].items()
    }


def _quote(value: object) -> str:
    """Render a scalar for YAML, quoting anything that could be misread.

    Digests contain a colon, and ports must not become YAML sexagesimals, so
    strings are always quoted and only booleans/ints are emitted bare.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(
    *,
    repo_root: pathlib.Path,
    declaration: ModuleDeclaration,
    names: ResourceNames,
    ports: dict[str, int],
    profile: str,
) -> str:
    """Return the Compose file text for one module's stack.

    ``ports`` maps logical names (postgres, api, frontend, ...) to allocated host
    ports. Every service binds to 127.0.0.1 explicitly: a development stack
    holding another school's synthetic data has no business being reachable from
    the local network.

    Does not handle: production deployment. That is M14's, and Kubernetes is not
    required.
    """
    images = load_images(repo_root)
    lines: list[str] = [
        "# GENERATED by dev/harness/compose.py -- do not edit by hand.",
        f"# module: {declaration.module_id} ({declaration.slug})  profile: {profile}",
        f"# project: {names.compose_project}",
        "#",
        "# Only the services this module declared in dev/modules/"
        f"{declaration.module_id}/module.json are present.",
        f"name: {_quote(names.compose_project)}",
        "",
        "services:",
    ]

    lines += _postgres(images, names, ports)
    if declaration.needs_broker:
        lines += _redis(images, ports)
    if declaration.needs_object_storage:
        lines += _minio(images, names, ports)
    lines += _api(images, declaration, names, ports, profile)
    if declaration.needs_worker:
        lines += _worker(images, declaration, names, ports, profile)
    if declaration.needs_frontend:
        lines += _frontend(images, ports)

    lines += ["", "volumes:"]
    lines += [
        f"  {names.volume_prefix}_postgres:",
        "    name: " + _quote(f"{names.volume_prefix}_postgres"),
    ]
    if declaration.needs_object_storage:
        lines += [
            f"  {names.volume_prefix}_objects:",
            "    name: " + _quote(f"{names.volume_prefix}_objects"),
        ]
    lines += [
        "",
        "networks:",
        "  default:",
        f"    name: {_quote(names.compose_project + '_net')}",
        "",
    ]
    return "\n".join(lines)


def _postgres(images: dict[str, str], names: ResourceNames, ports: dict[str, int]) -> list[str]:
    """Return the postgres service block. Required by every module."""
    return [
        "  postgres:",
        f"    image: {_quote(images['postgres'])}",
        "    environment:",
        f"      POSTGRES_DB: {_quote(names.database)}",
        f"      POSTGRES_USER: {_quote(LOCAL_DB_USER)}",
        f"      POSTGRES_PASSWORD: {_quote(LOCAL_DB_PASSWORD)}",
        "      # Deterministic collation, so ORDER BY is identical on every",
        "      # machine and keyset pagination cannot drift between developers.",
        '      LANG: "C"',
        '      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"',
        "    ports:",
        f'      - "127.0.0.1:{ports["postgres"]}:{POSTGRES_PORT}"',
        "    volumes:",
        f"      - {names.volume_prefix}_postgres:/var/lib/postgresql/data",
        "    healthcheck:",
        f'      test: ["CMD-SHELL", "pg_isready -U {LOCAL_DB_USER} -d {names.database}"]',
        '      interval: "2s"',
        '      timeout: "3s"',
        "      retries: 30",
        '    restart: "no"',
    ]


def _redis(images: dict[str, str], ports: dict[str, int]) -> list[str]:
    """Return the broker service block. Only for modules owning async work."""
    return [
        "  broker:",
        f"    image: {_quote(images['redis'])}",
        "    ports:",
        f'      - "127.0.0.1:{ports["broker"]}:{REDIS_PORT}"',
        "    healthcheck:",
        '      test: ["CMD", "redis-cli", "ping"]',
        '      interval: "2s"',
        '      timeout: "3s"',
        "      retries: 30",
        '    restart: "no"',
    ]


def _minio(images: dict[str, str], names: ResourceNames, ports: dict[str, int]) -> list[str]:
    """Return the private object storage block. Only for declaring modules."""
    return [
        "  object_storage:",
        f"    image: {_quote(images['minio'])}",
        '    command: ["server", "/data", "--console-address", ":9001"]',
        "    environment:",
        f"      MINIO_ROOT_USER: {_quote(LOCAL_MINIO_USER)}",
        f"      MINIO_ROOT_PASSWORD: {_quote(LOCAL_MINIO_PASSWORD)}",
        "    ports:",
        f'      - "127.0.0.1:{ports["object_storage"]}:{MINIO_API_PORT}"',
        f'      - "127.0.0.1:{ports["object_storage_console"]}:{MINIO_CONSOLE_PORT}"',
        "    volumes:",
        f"      - {names.volume_prefix}_objects:/data",
        "    healthcheck:",
        '      test: ["CMD", "mc", "ready", "local"]',
        '      interval: "3s"',
        '      timeout: "5s"',
        "      retries: 30",
        '    restart: "no"',
    ]


def _backend_environment(
    declaration: ModuleDeclaration,
    names: ResourceNames,
    ports: dict[str, int],
    profile: str,
) -> list[str]:
    """Return the environment block shared by the api and worker services.

    Secrets are read from the host environment (``${VAR}``), which ``dev.py``
    populates from dev/secrets -- never written into the generated file, because
    dev/state is not git-ignored by accident but by intent and a secret there
    would still be sitting in plaintext next to the checkout.

    Note the hostnames: inside the Compose network services reach each other by
    service name on the container port, not through the allocated host port.
    """
    block = [
        "    environment:",
        f"      APP_ENV: {_quote(profile)}",
        f"      MODULE_ID: {_quote(declaration.module_id)}",
        "      DATABASE_URL: "
        + _quote(
            f"postgresql://{LOCAL_DB_USER}:{LOCAL_DB_PASSWORD}"
            f"@postgres:{POSTGRES_PORT}/{names.database}"
        ),
        '      SESSION_SECRET: "${SESSION_SECRET}"',
        '      TOTP_ENCRYPTION_KEY: "${TOTP_ENCRYPTION_KEY}"',
        '      DEV_PERSONA_MODE: "fixed"',
        "      DJANGO_SETTINGS_MODULE: " + _quote(f"config.settings.{profile}"),
    ]
    if declaration.needs_broker:
        block.append("      BROKER_URL: " + _quote(f"redis://broker:{REDIS_PORT}/0"))
        block.append(
            "      WORKER_AVAILABLE: " + _quote("true" if declaration.needs_worker else "false")
        )
    if declaration.needs_object_storage:
        block += [
            "      OBJECT_STORAGE_ENDPOINT: "
            + _quote(f"http://object_storage:{MINIO_API_PORT}"),
            f"      OBJECT_STORAGE_BUCKET: {_quote(names.bucket)}",
            f"      OBJECT_STORAGE_ACCESS_KEY: {_quote(LOCAL_MINIO_USER)}",
            '      OBJECT_STORAGE_SECRET_KEY: "${OBJECT_STORAGE_SECRET_KEY}"',
        ]
    return block


def _api(
    images: dict[str, str],
    declaration: ModuleDeclaration,
    names: ResourceNames,
    ports: dict[str, int],
    profile: str,
) -> list[str]:
    """Return the Django API service block.

    Built from infra/backend.Dockerfile so dependencies come from the committed
    hash-pinned lockfiles. The source is bind-mounted so an edit is picked up by
    the autoreloader without a rebuild.
    """
    lines = [
        "  api:",
        "    build:",
        "      context: ..",
        "      dockerfile: infra/backend.Dockerfile",
        "      args:",
        f"        PYTHON_IMAGE: {_quote(images['python'])}",
    ]
    lines += _backend_environment(declaration, names, ports, profile)
    lines += [
        "    ports:",
        f'      - "127.0.0.1:{ports["api"]}:{API_PORT}"',
        "    volumes:",
        "      # Bind-mounted for autoreload. Read-only: the API has no reason to",
        "      # write into the developer's checkout.",
        "      - ../backend:/app/backend:ro",
        "      - ../contracts:/app/contracts:ro",
        "    depends_on:",
        "      postgres:",
        "        condition: service_healthy",
    ]
    if declaration.needs_broker:
        lines += ["      broker:", "        condition: service_healthy"]
    if declaration.needs_object_storage:
        lines += ["      object_storage:", "        condition: service_healthy"]
    lines += [
        "    healthcheck:",
        f'      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:{API_PORT}/healthz"]',
        '      interval: "3s"',
        '      timeout: "5s"',
        "      retries: 40",
        '    restart: "no"',
    ]
    return lines


def _worker(
    images: dict[str, str],
    declaration: ModuleDeclaration,
    names: ResourceNames,
    ports: dict[str, int],
    profile: str,
) -> list[str]:
    """Return the Celery worker block, for modules that own asynchronous work.

    A REAL worker against a REAL broker. Eager execution is never configured,
    because it cannot demonstrate crash or retry behaviour and B00 forbids
    claiming those results from it.
    """
    lines = [
        "  worker:",
        "    build:",
        "      context: ..",
        "      dockerfile: infra/backend.Dockerfile",
        "      args:",
        f"        PYTHON_IMAGE: {_quote(images['python'])}",
        "    command:",
        "      - celery",
        "      - -A",
        "      - config.celery:app",
        "      - worker",
        "      - --loglevel=info",
        "      - -Q",
        f"      - {names.queue}",
    ]
    lines += _backend_environment(declaration, names, ports, profile)
    lines += [
        "    volumes:",
        "      - ../backend:/app/backend:ro",
        "      - ../contracts:/app/contracts:ro",
        "    depends_on:",
        "      broker:",
        "        condition: service_healthy",
        "      postgres:",
        "        condition: service_healthy",
        '    restart: "no"',
    ]
    return lines


def _frontend(images: dict[str, str], ports: dict[str, int]) -> list[str]:
    """Return the Vite dev server block.

    VITE_SCHOOL_API_URL points at the HOST-published API port, not the container
    hostname: the browser resolves it, and the browser is outside the Compose
    network.
    """
    return [
        "  frontend:",
        "    build:",
        "      context: ..",
        "      dockerfile: infra/frontend.Dockerfile",
        "      args:",
        f"        NODE_IMAGE: {_quote(images['node'])}",
        "    environment:",
        "      VITE_SCHOOL_API_URL: " + _quote(f"http://127.0.0.1:{ports['api']}"),
        f"      SCHOOL_FRONTEND_PORT: {_quote(FRONTEND_PORT)}",
        "    ports:",
        f'      - "127.0.0.1:{ports["frontend"]}:{FRONTEND_PORT}"',
        "    volumes:",
        "      - ../frontend/src:/app/frontend/src:ro",
        "      - ../contracts:/app/contracts:ro",
        "    depends_on:",
        "      api:",
        "        condition: service_started",
        '    restart: "no"',
    ]


def required_port_names(declaration: ModuleDeclaration) -> tuple[str, ...]:
    """Return the logical port names this module's stack needs.

    All of these are containers. The api and frontend ports are published to the
    host so a developer's browser can reach them; inside the Compose network the
    services address each other by service name instead.
    """
    required = ["postgres", "api"]
    if declaration.needs_frontend:
        required.append("frontend")
    if declaration.needs_broker:
        required.append("broker")
    if declaration.needs_object_storage:
        required.extend(["object_storage", "object_storage_console"])
    return tuple(required)


def database_url(names: ResourceNames, ports: dict[str, int]) -> str:
    """Return the DSN the host-run Django process uses to reach the container."""
    return (
        f"postgresql://{LOCAL_DB_USER}:{LOCAL_DB_PASSWORD}"
        f"@127.0.0.1:{ports['postgres']}/{names.database}"
    )


def broker_url(ports: dict[str, int]) -> str:
    """Return the broker URL, for modules that declared one."""
    return f"redis://127.0.0.1:{ports['broker']}/0"


def object_storage_endpoint(ports: dict[str, int]) -> str:
    """Return the S3-compatible endpoint URL, for modules that declared one."""
    return f"http://127.0.0.1:{ports['object_storage']}"
