"""Renders a per-module Docker Compose file.

Only the services the module declared are emitted, so a module with no
asynchronous work produces a stack with no broker and no worker. The project
name, database, volumes, queue and bucket are all namespaced, which is what lets
two developers -- or one developer running two modules -- work simultaneously.

Images are pinned BY DIGEST from ``infra/images.json``, so a retagged upstream
image cannot change a stack underneath someone.

Emits YAML as text with no third-party dependency, because ``dev.py`` must run on
a fresh checkout before anything is installed. The emitter handles only the small
subset of YAML used here; it is not a general serialiser.
"""

from __future__ import annotations

import json
import pathlib

from .modules import ModuleDeclaration
from .naming import ResourceNames

#: Container-internal ports. Host ports are allocated dynamically.
POSTGRES_PORT = 5432
REDIS_PORT = 6379
MINIO_API_PORT = 9000
MINIO_CONSOLE_PORT = 9001
API_PORT = 8000
FRONTEND_PORT = 5173

#: Local development credentials for containers only. These are NOT secrets:
#: the services bind to loopback on a dynamically allocated port and hold only
#: synthetic fixture data. Real secrets live in dev/secrets/, outside Git.
LOCAL_DB_USER = "school_dev"
LOCAL_DB_PASSWORD = "school_dev_local_only"
LOCAL_MINIO_USER = "school_dev"
LOCAL_MINIO_PASSWORD = "school_dev_local_only"


def load_images(repo_root: pathlib.Path) -> dict[str, str]:
    """Return image name -> fully pinned digest reference.

    Raises FileNotFoundError with a pointer to the file when the pin record is
    missing, rather than falling back to a floating tag.
    """
    path = repo_root / "infra" / "images.json"
    if not path.exists():
        raise FileNotFoundError(
            f"{path} is missing; images must be pinned by digest, never floated."
        )
    record = json.loads(path.read_text())
    return {
        name: f"{image['registry']}/{image['repository']}@{image['digest']}"
        for name, image in record["images"].items()
    }


def _quote(value: object) -> str:
    """Render a scalar for YAML, quoting anything that could be misread.

    Digests contain a colon, and ports must not become YAML sexagesimals, so
    strings are always quoted and only booleans/ints are emitted bare.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(
    *,
    repo_root: pathlib.Path,
    declaration: ModuleDeclaration,
    names: ResourceNames,
    ports: dict[str, int],
    profile: str,
) -> str:
    """Return the Compose file text for one module's stack.

    ``ports`` maps logical names (postgres, api, frontend, ...) to allocated host
    ports. Every service binds to 127.0.0.1 explicitly: a development stack
    holding another school's synthetic data has no business being reachable from
    the local network.

    Does not handle: production deployment. That is M14's, and Kubernetes is not
    required.
    """
    images = load_images(repo_root)
    lines: list[str] = [
        "# GENERATED by dev/harness/compose.py -- do not edit by hand.",
        f"# module: {declaration.module_id} ({declaration.slug})  profile: {profile}",
        f"# project: {names.compose_project}",
        "#",
        "# Only the services this module declared in dev/modules/"
        f"{declaration.module_id}/module.json are present.",
        f"name: {_quote(names.compose_project)}",
        "",
        "services:",
    ]

    lines += _postgres(images, names, ports)
    if declaration.needs_broker:
        lines += _redis(images, ports)
    if declaration.needs_object_storage:
        lines += _minio(images, names, ports)

    lines += ["", "volumes:"]
    lines += [
        f"  {names.volume_prefix}_postgres:",
        "    name: " + _quote(f"{names.volume_prefix}_postgres"),
    ]
    if declaration.needs_object_storage:
        lines += [
            f"  {names.volume_prefix}_objects:",
            "    name: " + _quote(f"{names.volume_prefix}_objects"),
        ]
    lines += [
        "",
        "networks:",
        "  default:",
        f"    name: {_quote(names.compose_project + '_net')}",
        "",
    ]
    return "\n".join(lines)


def _postgres(images: dict[str, str], names: ResourceNames, ports: dict[str, int]) -> list[str]:
    """Return the postgres service block. Required by every module."""
    return [
        "  postgres:",
        f"    image: {_quote(images['postgres'])}",
        "    environment:",
        f"      POSTGRES_DB: {_quote(names.database)}",
        f"      POSTGRES_USER: {_quote(LOCAL_DB_USER)}",
        f"      POSTGRES_PASSWORD: {_quote(LOCAL_DB_PASSWORD)}",
        "      # Deterministic collation, so ORDER BY is identical on every",
        "      # machine and keyset pagination cannot drift between developers.",
        '      LANG: "C"',
        '      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"',
        "    ports:",
        f'      - "127.0.0.1:{ports["postgres"]}:{POSTGRES_PORT}"',
        "    volumes:",
        f"      - {names.volume_prefix}_postgres:/var/lib/postgresql/data",
        "    healthcheck:",
        f'      test: ["CMD-SHELL", "pg_isready -U {LOCAL_DB_USER} -d {names.database}"]',
        '      interval: "2s"',
        '      timeout: "3s"',
        "      retries: 30",
        '    restart: "no"',
    ]


def _redis(images: dict[str, str], ports: dict[str, int]) -> list[str]:
    """Return the broker service block. Only for modules owning async work."""
    return [
        "  broker:",
        f"    image: {_quote(images['redis'])}",
        "    ports:",
        f'      - "127.0.0.1:{ports["broker"]}:{REDIS_PORT}"',
        "    healthcheck:",
        '      test: ["CMD", "redis-cli", "ping"]',
        '      interval: "2s"',
        '      timeout: "3s"',
        "      retries: 30",
        '    restart: "no"',
    ]


def _minio(images: dict[str, str], names: ResourceNames, ports: dict[str, int]) -> list[str]:
    """Return the private object storage block. Only for declaring modules."""
    return [
        "  object_storage:",
        f"    image: {_quote(images['minio'])}",
        '    command: ["server", "/data", "--console-address", ":9001"]',
        "    environment:",
        f"      MINIO_ROOT_USER: {_quote(LOCAL_MINIO_USER)}",
        f"      MINIO_ROOT_PASSWORD: {_quote(LOCAL_MINIO_PASSWORD)}",
        "    ports:",
        f'      - "127.0.0.1:{ports["object_storage"]}:{MINIO_API_PORT}"',
        f'      - "127.0.0.1:{ports["object_storage_console"]}:{MINIO_CONSOLE_PORT}"',
        "    volumes:",
        f"      - {names.volume_prefix}_objects:/data",
        "    healthcheck:",
        '      test: ["CMD", "mc", "ready", "local"]',
        '      interval: "3s"',
        '      timeout: "5s"',
        "      retries: 30",
        '    restart: "no"',
    ]


def required_port_names(declaration: ModuleDeclaration) -> tuple[str, ...]:
    """Return the logical port names this module's stack needs.

    ``api`` and ``frontend`` are host-run processes rather than containers in the
    development profile, but they still need reserved ports so that two
    simultaneous stacks do not both try to serve on the same one.
    """
    required = ["postgres", "api"]
    if declaration.needs_frontend:
        required.append("frontend")
    if declaration.needs_broker:
        required.append("broker")
    if declaration.needs_object_storage:
        required.extend(["object_storage", "object_storage_console"])
    return tuple(required)


def database_url(names: ResourceNames, ports: dict[str, int]) -> str:
    """Return the DSN the host-run Django process uses to reach the container."""
    return (
        f"postgresql://{LOCAL_DB_USER}:{LOCAL_DB_PASSWORD}"
        f"@127.0.0.1:{ports['postgres']}/{names.database}"
    )


def broker_url(ports: dict[str, int]) -> str:
    """Return the broker URL, for modules that declared one."""
    return f"redis://127.0.0.1:{ports['broker']}/0"


def object_storage_endpoint(ports: dict[str, int]) -> str:
    """Return the S3-compatible endpoint URL, for modules that declared one."""
    return f"http://127.0.0.1:{ports['object_storage']}"
