# Generated by Django 6.1.1 on 2026-09-20 17:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('year_id', models.UUIDField()),
                ('term_id', models.UUIDField()),
                ('section_id', models.UUIDField()),
                ('subject_id', models.UUIDField()),
                ('type', models.CharField(choices=[('assignment', 'assignment'), ('written_test', 'written_test'), ('practical', 'practical'), ('project', 'project')], max_length=32)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('policy_version', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('approved', 'approved'), ('published', 'published'), ('reopened', 'reopened')], default='draft', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('marks_author_id', models.UUIDField(blank=True, null=True)),
                ('require_distinct_approver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'assessment_assessment',
                'indexes': [models.Index(fields=['school_id', 'term_id'], name='assessment__school__9bdd3a_idx'), models.Index(fields=['school_id', 'section_id', 'subject_id'], name='assessment__school__08c478_idx')],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField()),
                ('approved_at', models.DateTimeField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='assessment.assessment')),
            ],
            options={
                'db_table': 'assessment_approval',
                'ordering': ['approved_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('question_type', models.CharField(blank=True, max_length=80, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assessment.assessment')),
            ],
            options={
                'db_table': 'assessment_component',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField()),
                ('result_revision_ids', models.JSONField()),
                ('actor_id', models.UUIDField()),
                ('published_at', models.DateTimeField()),
                ('report_job_id', models.CharField(blank=True, default='', max_length=128)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='assessment.assessment')),
            ],
            options={
                'db_table': 'assessment_publication',
                'ordering': ['published_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublishIdempotency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField()),
                ('assessment_id', models.UUIDField()),
                ('idempotency_key', models.CharField(max_length=128)),
                ('publication_id', models.UUIDField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'assessment_publish_idempotency',
                'constraints': [models.UniqueConstraint(fields=('school_id', 'assessment_id', 'idempotency_key'), name='assessment_publish_idem_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField()),
                ('attempt_id', models.UUIDField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('approved', 'approved'), ('published', 'published'), ('reopened', 'reopened')], default='draft', max_length=16)),
                ('marking_outcome', models.CharField(choices=[('scored', 'scored'), ('absent', 'absent'), ('exempt', 'exempt'), ('oral', 'oral'), ('practical', 'practical')], default='scored', max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('version', models.IntegerField(default=1)),
                ('current_revision_id', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessment.assessment')),
            ],
            options={
                'db_table': 'assessment_result',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_id', models.UUIDField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='assessment.result')),
            ],
            options={
                'db_table': 'assessment_mark',
            },
        ),
        migrations.CreateModel(
            name='EvidenceBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('file_id', models.UUIDField()),
                ('file_version', models.IntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('page_no', models.IntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_bindings', to='assessment.result')),
            ],
            options={
                'db_table': 'assessment_evidence_binding',
                'ordering': ['page_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResultRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField()),
                ('snapshot', models.JSONField()),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='assessment.result')),
            ],
            options={
                'db_table': 'assessment_result_revision',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['school_id', 'student_id'], name='assessment__school__17ea71_idx'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('assessment', 'student_id', 'attempt_id'), name='assessment_result_attempt_uniq'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('result', 'component_id'), name='assessment_mark_component_uniq'),
        ),
    ]
