# Generated by Django 6.1.1 on 2026-09-19 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('board', models.CharField(default='CBSE', max_length=16)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam')], default='en', max_length=2)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'registry_school_config',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=64)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('state', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('closed', 'closed'), ('archived', 'archived')], default='draft', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'registry_academic_year',
                'constraints': [models.UniqueConstraint(fields=('school_id', 'name'), name='registry_year_unique_name_per_school')],
            },
        ),
        migrations.CreateModel(
            name='DuplicateReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField()),
                ('input_digest', models.CharField(max_length=64)),
                ('candidates', models.JSONField(default=list)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'registry_duplicate_review',
                'indexes': [models.Index(fields=['school_id', 'actor_id'], name='registry_du_school__a3ec74_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(max_length=16)),
                ('person_id', models.UUIDField(db_index=True)),
                ('source', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'registry_external_identity',
                'constraints': [models.UniqueConstraint(fields=('school_id', 'source', 'kind', 'value'), name='registry_external_identity_unique_mapping')],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('display_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'registry_guardian',
                'indexes': [models.Index(fields=['school_id', 'archived'], name='registry_gu_school__9e9f0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('display_name', models.CharField(max_length=200)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'registry_staff_profile',
                'indexes': [models.Index(fields=['school_id', 'archived'], name='registry_st_school__98be89_idx')],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('number', models.IntegerField()),
                ('archived', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'registry_standard',
                'constraints': [models.UniqueConstraint(fields=('school_id', 'number'), name='registry_standard_unique_number_per_school')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('admission_no', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam')], default='en', max_length=2)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('transferred', 'transferred'), ('graduated', 'graduated')], default='active', max_length=16)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'registry_student',
                'indexes': [models.Index(fields=['school_id', 'status'], name='registry_st_school__615336_idx'), models.Index(fields=['school_id', 'display_name', 'date_of_birth'], name='registry_st_school__66cda7_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'admission_no'), name='registry_student_unique_admission_per_school')],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=32)),
                ('display_name', models.CharField(max_length=128)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'registry_subject',
                'constraints': [models.UniqueConstraint(fields=('school_id', 'code'), name='registry_subject_unique_code_per_school')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=32)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='registry.academicyear')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='registry.standard')),
            ],
            options={
                'db_table': 'registry_section',
                'indexes': [models.Index(fields=['school_id', 'year', 'archived'], name='registry_se_school__203d51_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'year', 'standard', 'name'), name='registry_section_unique_name_per_standard_year')],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=64)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('archived', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='registry.academicyear')),
            ],
            options={
                'db_table': 'registry_term',
                'constraints': [models.UniqueConstraint(fields=('school_id', 'year', 'name'), name='registry_term_unique_name_per_year')],
            },
        ),
    ]
