# Generated by Django 6.1.1 on 2026-09-21 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('previous_enrolment_id', models.UUIDField(blank=True, null=True)),
                ('state', models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled')], default='active', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='registry.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='registry.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='registry.academicyear')),
            ],
            options={
                'db_table': 'registry_enrolment',
            },
        ),
        migrations.CreateModel(
            name='GuardianLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('visibility', models.CharField(choices=[('academic', 'academic'), ('none', 'none')], max_length=16)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_links', to='registry.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_links', to='registry.student')),
            ],
            options={
                'db_table': 'registry_guardian_link',
            },
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('optional_group', models.CharField(blank=True, max_length=64, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_offerings', to='registry.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='registry.subject')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_offerings', to='registry.academicyear')),
            ],
            options={
                'db_table': 'registry_subject_offering',
            },
        ),
        migrations.CreateModel(
            name='SubjectEnrolment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_enrolments', to='registry.enrolment')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_enrolments', to='registry.subjectoffering')),
            ],
            options={
                'db_table': 'registry_subject_enrolment',
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='registry.section')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='registry.staffprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='registry.subject')),
            ],
            options={
                'db_table': 'registry_teaching_assignment',
            },
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['school_id', 'student'], name='registry_en_school__ca77d1_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['school_id', 'section'], name='registry_en_school__e2157d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['school_id', 'year', 'state'], name='registry_en_school__c285b3_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianlink',
            index=models.Index(fields=['school_id', 'student'], name='registry_gu_school__7d644c_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianlink',
            index=models.Index(fields=['school_id', 'guardian'], name='registry_gu_school__21c5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectoffering',
            index=models.Index(fields=['school_id', 'section', 'archived'], name='registry_su_school__6e4bc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.UniqueConstraint(fields=('school_id', 'year', 'section', 'subject'), name='registry_offering_unique_subject_per_section_year'),
        ),
        migrations.AddIndex(
            model_name='subjectenrolment',
            index=models.Index(fields=['school_id', 'enrolment'], name='registry_su_school__7c65db_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectenrolment',
            index=models.Index(fields=['school_id', 'subject_offering'], name='registry_su_school__3ec94d_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['school_id', 'staff'], name='registry_te_school__f21263_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['school_id', 'section'], name='registry_te_school__468675_idx'),
        ),
    ]
