# Generated by Django 6.1.1 on 2026-09-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_lifecycle_links_enrolments'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
