# Generated by Django 6.1.1 on 2026-09-20 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolment_id', models.UUIDField()),
                ('student_id', models.UUIDField()),
                ('status', models.CharField(choices=[('unmarked', 'unmarked'), ('present', 'present'), ('absent', 'absent'), ('late', 'late'), ('excused', 'excused')], default='unmarked', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('version', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'attendance_entry',
            },
        ),
        migrations.CreateModel(
            name='AttendanceAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('unmarked', 'unmarked'), ('present', 'present'), ('absent', 'absent'), ('late', 'late'), ('excused', 'excused')], max_length=16)),
                ('new_status', models.CharField(choices=[('unmarked', 'unmarked'), ('present', 'present'), ('absent', 'absent'), ('late', 'late'), ('excused', 'excused')], max_length=16)),
                ('reason', models.CharField(max_length=500)),
                ('actor_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='attendance.attendanceentry')),
            ],
            options={
                'db_table': 'attendance_amendment',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('timetable_session_id', models.UUIDField()),
                ('date', models.DateField()),
                ('section_id', models.UUIDField()),
                ('slot_id', models.UUIDField()),
                ('subject_id', models.UUIDField()),
                ('timetable_version', models.IntegerField()),
                ('roster_version', models.IntegerField()),
                ('roster_snapshot', models.JSONField()),
                ('state', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted')], default='draft', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('reconciliation_reason', models.TextField(blank=True, default='')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance_session',
                'indexes': [models.Index(fields=['school_id', 'date'], name='attendance__school__e4f52c_idx'), models.Index(fields=['school_id', 'section_id', 'date'], name='attendance__school__e7c5c2_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'timetable_session_id'), name='attendance_session_school_timetable_uniq')],
            },
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='attendance.attendancesession'),
        ),
        migrations.CreateModel(
            name='SubmitIdempotency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'attendance_submit_idempotency',
                'constraints': [models.UniqueConstraint(fields=('school_id', 'session_id', 'idempotency_key'), name='attendance_submit_idem_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendanceentry',
            constraint=models.UniqueConstraint(fields=('session', 'enrolment_id'), name='attendance_entry_session_enrolment_uniq'),
        ),
    ]
