# Generated by Django 6.1.1 on 2026-09-19 02:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('section_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('subject_person_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('body', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'demo_note',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['school_id', 'created_at', 'id'], name='demo_note_school__c45140_idx')],
            },
        ),
    ]
