# Generated by Django 6.1.1 on 2026-09-21 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('db_point', models.CharField(max_length=256)),
                ('object_versions', models.JSONField(default=list)),
                ('fee_total_paise', models.PositiveIntegerField(blank=True, null=True)),
                ('record_counts', models.JSONField(default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'platform_backup_manifest',
            },
        ),
        migrations.CreateModel(
            name='PlatformPolicy',
            fields=[
                ('school_id', models.UUIDField(primary_key=True, serialize=False)),
                ('backup_age_alert_minutes', models.PositiveIntegerField(default=20)),
                ('rpo_minutes_hypothesis', models.PositiveIntegerField(default=15)),
                ('rto_hours_hypothesis', models.PositiveIntegerField(default=4)),
            ],
            options={
                'db_table': 'platform_policy',
            },
        ),
        migrations.CreateModel(
            name='RestoreRehearsal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField()),
                ('backup_manifest_id', models.UUIDField()),
                ('isolated_target_label', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('verified', 'verified'), ('failed', 'failed')], default='queued', max_length=16)),
                ('record_counts', models.JSONField(default=dict)),
                ('object_hashes_matched', models.BooleanField(default=False)),
                ('fee_total_paise', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_restore_rehearsal',
            },
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField()),
                ('action', models.CharField(max_length=128)),
                ('resource_id', models.UUIDField(db_index=True)),
                ('occurred_at', models.DateTimeField()),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'platform_audit_record',
                'indexes': [models.Index(fields=['school_id', 'action', 'occurred_at'], name='platform_au_school__f0e11d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsumerReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer', models.CharField(max_length=128)),
                ('event_id', models.UUIDField()),
                ('school_id', models.UUIDField(db_index=True)),
                ('received_at', models.DateTimeField()),
                ('side_effect_token', models.CharField(default='', max_length=128)),
            ],
            options={
                'db_table': 'platform_consumer_receipt',
                'constraints': [models.UniqueConstraint(fields=('consumer', 'event_id'), name='platform_consumer_receipt_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField()),
                ('kind', models.CharField(max_length=128)),
                ('payload_ref', models.CharField(max_length=512)),
                ('state', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('dead', 'dead')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=128, null=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'platform_job',
                'indexes': [models.Index(fields=['school_id', 'state'], name='platform_jo_school__f18d29_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'kind', 'idempotency_key'), name='platform_job_idempotency_uniq')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('occurred_at', models.DateTimeField()),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('aggregate_version', models.IntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('envelope_version', models.IntegerField(default=1)),
                ('correlation_id', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('dispatching', 'dispatching'), ('dispatched', 'dispatched'), ('failed', 'failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_outbox_event',
                'indexes': [models.Index(fields=['state', 'occurred_at'], name='platform_ou_state_4ac76c_idx')],
            },
        ),
    ]
