# Generated by Django 6.1.1 on 2026-09-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='task_path',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
