# Generated by Django 6.1.1 on 2026-09-20 20:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(unique=True)),
                ('transfer_include_as_alumni', models.BooleanField(blank=True, null=True)),
                ('alumni_login_enabled', models.BooleanField(default=False)),
                ('exportable_fields', models.JSONField(default=list)),
                ('granted_contact_purposes', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'alumni_policy',
            },
        ),
        migrations.CreateModel(
            name='ContactAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('profile_id', models.UUIDField(db_index=True)),
                ('old_json', models.JSONField()),
                ('new_json', models.JSONField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('actor_id', models.UUIDField()),
            ],
            options={
                'db_table': 'alumni_contact_amendment',
            },
        ),
        migrations.CreateModel(
            name='AlumniCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('leaving_event_id', models.UUIDField()),
                ('outcome', models.CharField(choices=[('graduate', 'graduate'), ('transfer', 'transfer')], max_length=16)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('excluded', 'excluded')], default='pending', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('admission_no', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=256)),
                ('last_standard', models.IntegerField()),
                ('leaving_year', models.IntegerField()),
            ],
            options={
                'db_table': 'alumni_candidate',
                'indexes': [models.Index(fields=['school_id', 'state'], name='alumni_cand_school__101dc2_idx'), models.Index(fields=['school_id', 'leaving_event_id'], name='alumni_cand_school__7c99f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'student_id', 'leaving_event_id'), name='alumni_candidate_school_student_event_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('candidate_id', models.UUIDField()),
                ('last_standard', models.IntegerField()),
                ('leaving_year', models.IntegerField()),
                ('outcome', models.CharField(choices=[('graduate', 'graduate'), ('transfer', 'transfer')], max_length=16)),
                ('snapshot_version', models.IntegerField(default=1)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('postal_address', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('display_name', models.CharField(max_length=256)),
                ('admission_no', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'alumni_profile',
                'indexes': [models.Index(fields=['school_id', 'leaving_year'], name='alumni_prof_school__7a1def_idx'), models.Index(fields=['school_id', 'outcome'], name='alumni_prof_school__16fdd8_idx')],
                'constraints': [models.UniqueConstraint(fields=('school_id', 'student_id'), name='alumni_profile_school_student_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ContactPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(db_index=True)),
                ('profile_id', models.UUIDField(db_index=True)),
                ('person_id', models.UUIDField()),
                ('purpose', models.CharField(choices=[('alumni_notice', 'alumni_notice'), ('directory', 'directory')], max_length=32)),
                ('channel', models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('postal', 'postal'), ('phone', 'phone')], max_length=16)),
                ('allowed', models.BooleanField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'alumni_contact_preference',
                'constraints': [models.UniqueConstraint(fields=('profile_id', 'purpose', 'channel'), name='alumni_pref_profile_purpose_channel_uniq')],
            },
        ),
    ]
