"""Synthetic names for demo people. Combinations, not real individuals."""

from __future__ import annotations

import random

FIRST_NAMES_BOYS = (
    "Aarav",
    "Adarsh",
    "Adithya",
    "Akhil",
    "Alan",
    "Amal",
    "Anand",
    "Arjun",
    "Ashwin",
    "Basil",
    "Deepak",
    "Dev",
    "Farhan",
    "Gautham",
    "Hari",
    "Ibrahim",
    "Jithin",
    "Joel",
    "Karthik",
    "Kiran",
    "Midhun",
    "Mohammed",
    "Nakul",
    "Naveen",
    "Nikhil",
    "Pranav",
    "Rahul",
    "Rohan",
    "Sachin",
    "Sanjay",
    "Sidharth",
    "Vishnu",
    "Vivek",
    "Yadu",
)
FIRST_NAMES_GIRLS = (
    "Aditi",
    "Aishwarya",
    "Amina",
    "Ananya",
    "Anjali",
    "Aparna",
    "Athira",
    "Bhavya",
    "Devika",
    "Diya",
    "Fathima",
    "Gayathri",
    "Gopika",
    "Hiba",
    "Keerthana",
    "Lakshmi",
    "Malavika",
    "Meera",
    "Nandana",
    "Neha",
    "Niranjana",
    "Parvathy",
    "Riya",
    "Sneha",
    "Sreelakshmi",
    "Swathi",
    "Theertha",
    "Varsha",
    "Vismaya",
    "Zara",
)
SURNAMES = (
    "Nair",
    "Menon",
    "Pillai",
    "Kurup",
    "Varghese",
    "Thomas",
    "Joseph",
    "Mathew",
    "Kumar",
    "Das",
    "Krishnan",
    "Raj",
    "Ali",
    "Rahman",
    "Abraham",
    "George",
    "Namboothiri",
    "Warrier",
    "Panicker",
    "Iyer",
    "Chacko",
    "Philip",
    "Babu",
    "Mohan",
)
PARENT_FIRST = (
    "Suresh",
    "Rajesh",
    "Anil",
    "Sunil",
    "Biju",
    "Shaji",
    "Manoj",
    "Prakash",
    "Rajeev",
    "Sajan",
    "Thomas",
    "Jose",
    "Abdul",
    "Ramesh",
    "Vinod",
    "Sreekumar",
    "Latha",
    "Bindu",
    "Sheela",
    "Deepa",
    "Rekha",
    "Smitha",
    "Jaya",
    "Priya",
    "Sindhu",
    "Asha",
)


def student_name(rng: random.Random) -> str:
    """Return a synthetic student name."""
    first = rng.choice(FIRST_NAMES_BOYS if rng.random() < 0.5 else FIRST_NAMES_GIRLS)
    return f"{first} {rng.choice(SURNAMES)}"


def parent_name(rng: random.Random, surname: str) -> str:
    """Return a synthetic parent name sharing the child's surname."""
    return f"{rng.choice(PARENT_FIRST)} {surname}"
